server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ace?characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


mybatis:
  mapper-locations: classpath:com/ace2/mybatisplug/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


logging:
  level:
    com:
      example:
        mapper: debug

